[package]
name = "laba17"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
dialoguer = "0.12.0"

[[bin]]
name = "laba17"
path = "src/main.rs"

[[bin]]
name = "task2"
path = "src2/main.rs"

[[bin]]
name = "task3"
path = "src3/main.rs"
